name: aix-core
version: '30.0'
summary: Fully validating Aix peer-to-peer network node, wallet and GUI
description: |
  Aix Core connects to the Aix peer-to-peer network to download and
  fully validate blocks and transactions. It also includes a wallet and
  graphical user interface.

grade: stable
confinement: strict
base: core22

apps:
  daemon:
    command: bin/aixd
    plugs: [home, removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at
      # ~/snap/aix-core/common/.aix/ instead of
      # ~/snap/aix-core/current/.aix/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: bin/desktop-launch aix-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: bin/aix-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  tx:
    command: bin/aix-tx
    environment:
      HOME: $SNAP_USER_COMMON
  wallet:
    command: bin/aix-wallet
    plugs: [home, removable-media]
    environment:
      HOME: $SNAP_USER_COMMON
  util:
    command: bin/aix-util
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  desktop-launch:
    source: ./snap/local/src
    plugin: make
    stage-packages:
      - libxkbcommon0
      - fonts-ubuntu
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  aix-core:
    plugin: nil
    override-build: |
      env | grep "CRAFT\|SNAP" | sort
      aix_core_version=$(craftctl get version)
      curl -LO https://aixcore.org/bin/aix-core-${aix_core_version}/SHA256SUMS
      curl -LO https://aixcore.org/bin/aix-core-${aix_core_version}/aix-${aix_core_version}.tar.gz
      curl -LO https://aixcore.org/bin/aix-core-${aix_core_version}/aix-${aix_core_version}-${CRAFT_ARCH_TRIPLET_BUILD_FOR}.tar.gz
      echo "bff6f5c133ab78a89fa56908ad4109b06692a3b2c5b38a67ed880137cf1d3bda  SHA256SUMS" | sha256sum --check
      sha256sum --ignore-missing --check SHA256SUMS
      tar -xvf aix-${aix_core_version}-${CRAFT_ARCH_TRIPLET_BUILD_FOR}.tar.gz
      tar -xvf aix-${aix_core_version}.tar.gz
      echo "Running tests ..."
      aix-${aix_core_version}/libexec/test_aix
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin aix-${aix_core_version}/bin/aixd
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin aix-${aix_core_version}/bin/aix-qt
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin aix-${aix_core_version}/bin/aix-cli
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin aix-${aix_core_version}/bin/aix-tx
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin aix-${aix_core_version}/bin/aix-wallet
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin aix-${aix_core_version}/bin/aix-util
      curl -LO https://raw.githubusercontent.com/aix/aix/v${aix_core_version}/share/pixmaps/aix128.png
      install -m 0644 -D -t $CRAFT_PART_INSTALL/share/pixmaps aix128.png
    build-packages:
      - curl
    after:
      - desktop-launch
